### PR TITLE
Make API more C# like

### PR DESCRIPTION
**Pull request by tripplet**

### CODE REVIEW

**Comment by tripplet** [comment]
~~The only functional change is in the finalizer, I used `Dispose(false);` instead of `Dispose(true);` which is what microsoft recommends, see https://msdn.microsoft.com/en-us/library/system.idisposable.dispose(v=vs.110).aspx~~

Sorry I confused this with changes I made earlier to PS6000PinnedArray.cs

**Comment by hsmistry** [comment]
@tripplet Thanks for the Pull request. We will review this and get back to you.

**Comment by sometraveller** [comment]
That makes work much easier! Thanks a lot @tripplet !

**Comment by pigrew** [comment]
It seems that the TC08 library has its own pinned array class. Perhaps the changes need to be merged into both? (I don't know why it has its own pinned array class instead of using the shared one)

**Comment by hsmistry** [comment]
@pigrew, the pinned array class is a separate issue. We are in the process of updating the examples to use a common PicoPinnedArray class.

**Review by hsmistry — APPROVED** [review]
Accepted change

**Review by hsmistry — APPROVED** [review]
Accept changes

**Comment by hsmistry** [comment]
Couple of slight modifications after review: see Changesets cde07ef & a3a4fd1.

@tripplet, thanks for the pull request! 👍

**Pull request merged**
